### ISSUE TITLE
Initial plugin

### ISSUE THREAD

**Issue by simonw** [datasette/datasette-examples#1]
in `datasette.yml`:
```yaml
plugins:
  datasette-examples:
    startup:
      examples:
      - url: https://s3.amazonaws.com/datasette-examples/legislators.sql
        if_not_table: congress_executives
      - url: https://s3.amazonaws.com/datasette-examples/global-power-plants.sql
        if_not_table: global_power_plants
```
On startup, run the SQL if the table doesn't exist.
